### ISSUE TITLE
ngx-jodit-pro:Property 'font' must be of type 'HTMLFontElement', but here has type 'HTMLElement'.

### ISSUE THREAD

**Issue by Yang-Jing-Hui** [julianpoemp/ngx-jodit#10]
**Message：**
Error: node_modules/jodit/types/types/types.d.ts:280:3 - error TS2717: Subsequent property declarations must have the same type. Property 'font' must be of type 'HTMLFontElement', but here has type 'HTMLElement'.
280 font: HTMLElement;

node_modules/typescript/lib/lib.dom.d.ts:17141:5
17141 "font": HTMLFontElement;

'font' was also declared here.

**package version：**
package.json：
"dependencies": {
"@angular/cdk": "13.3.9",
"@angular/common": "13.3.11",
"@angular/compiler": "13.3.11",
"@angular/core": "13.3.11",
....
"jodit": "3.24.9",
"jodit-pro": "^1.3.40",
"ngx-jodit-pro": "^1.0.2",
...
},
"devDependencies": {
....
"typescript": "4.6.4"
}

**Comment by julianpoemp** [comment]
@Yang-Jing-Hui please this:

>Add "skipLibCheck": true to compilerOptions in your tsconfig.app.json. This is needed because the check fails to typing errors of the jodit package. If you know any other solution, let me know :):
````
...
  "compilerOptions": {
    ...,
    "skipLibCheck": true
  }
...
````

**Comment by Yang-Jing-Hui** [comment]
@julianpoemp Thank you! This issue has been resolved.
Haha, I also found the same solution.
