### ISSUE TITLE
ngx-jodit-pro:Can ngModel be supported?

### ISSUE THREAD

**Issue by Yang-Jing-Hui** [julianpoemp/ngx-jodit#14]
<ngx-jodit-pro [(value)]="value" [(options)]="options"></ngx-jodit>
 
 When I update the value in typescript, the new value is not work in the jodit editor.

**Comment by julianpoemp** [comment]
@Yang-Jing-Hui thank you for reporting this. I released new versions. Please update ngx-jodit-pro to the next minor version. (See [versions](https://www.npmjs.com/package/ngx-jodit-pro?activeTab=versions)).

If you face any problem with ngModel, I suggest you to use valueChange and value separately:

````html
<ngx-jodit-pro (valueChange)="onValueChange($event)" [value]="value"></ngx-jodit-pro>
````
