### ISSUE TITLE
ngx-jodit: TypeScript warning

### ISSUE THREAD

**Issue by elementalPRESS** [julianpoemp/ngx-jodit#17]
Hi,

today I tried your latest version of the wrapper. Great work! But there is a "small" issue. When compiling I always get the following warning:

	Warning: /Volumes/Daten/Websites/SSCM.v3/node_modules/jodit/types/types/storage.ts is part of the TypeScript compilation but it's unused.
	Add only entry points to the 'files' or 'include' properties in your tsconfig.

I'm using the most recent Angular (16.2.5) and ngx-jodit (ngx-jodit@3.0.0-beta.8) and jodit 3.24.9

Pls can you fix this?

**Comment by julianpoemp** [comment]
Hi @elementalPRESS 

did you try to add this:

> Add "skipLibCheck": true to compilerOptions in your tsconfig.app.json. This is needed because the check fails to typing errors of the jodit package. If you know any other solution, let me know :):
```` 
...
  "compilerOptions": {
    ...,
    "skipLibCheck": true
  }
...
````
?

If this doesn't fix it unfortunately I can't help with this issue, because it's an error from Jodit package itself...

**Comment by elementalPRESS** [comment]
> > Add "skipLibCheck": true to compilerOptions in your tsconfig.app.json. This is needed because the check fails to typing errors of the jodit package. If you know any other solution, let me know :):

I have `skipLibCheck` enabled. Thank you for your feedback.

**Comment by julianpoemp** [comment]
if this issue still exists, please report it to Jodit. Btw. ngx-jodit 3 is only compatible to jodit 4.

**Comment by julianpoemp** [comment]
@elementalPRESS I just released a new version of ngx-jodit v2 and v3. Because of typing issues we have to use compiled JS files from Jodit. But this could "solve" your problem. Can you please test if this issue still exists with the latest version of v2 or v3 (and latest version of jodit 4)?

**Comment by elementalPRESS** [comment]
> @elementalPRESS I just released a new version of ngx-jodit v2 and v3. Because of typing issues we have to use compiled JS files from Jodit. But this could "solve" your problem. Can you please test if this issue still exists with the latest version of v2 or v3 (and latest version of jodit 4)?

Hi Julian,

thx for your effort. I've updated the version and started the compiler. Runs smoothly and the typing error is gone. But now unfortunately I get:

    ReferenceError: Jodit is not defined
        at NgxJoditComponent.initJoditContainer (ngx-jodit.mjs:68:26)
        at NgxJoditComponent.ngAfterViewInit (ngx-jodit.mjs:61:14)
        at callHookInternal (core.mjs:3920:14)
        at callHook (core.mjs:3947:13)
        at callHooks (core.mjs:3902:17)
        at executeInitAndCheckHooks (core.mjs:3852:9)
        at refreshView (core.mjs:13552:21)
        at detectChangesInView (core.mjs:13646:9)
        at detectChangesInComponent (core.mjs:13621:5)
        at detectChangesInChildComponents (core.mjs:13659:9)

**Comment by julianpoemp** [comment]
@elementalPRESS please add the jodit js file to the scripts attribute in your angular.json/project.json as described in the installation instructions

**Comment by julianpoemp** [comment]
@elementalPRESS The issue with ESM was resolved. I just released new versions for ngx-jodit v2 and v3 with ESM support. Now you can use the ESM version of Jodit with working typings. Please have a look on the installation instructions for breaking changes:

- [README for ngx-jodit v2](https://www.npmjs.com/package/ngx-jodit/v/2x#installation)
- [README for ngx-jodit v3](https://www.npmjs.com/package/ngx-jodit/v/3x#installation)

Of course you can now remove the JS file from "scripts".

I'm closing this issue. Let me know if it still exists.
