### ISSUE TITLE
ngx-jodit: pressing Ctrl + x (cut) doesn't trigger (valueChange)

### ISSUE THREAD

**Issue by ptatoChi** [julianpoemp/ngx-jodit#21]
I noticed that when doing ctrl + x doesnt emit a value from valueChange

` <ngx-jodit #joditeditor [value]="templateValue()" [options]="options" (valueChange)="onValueChange($event)"></ngx-jodit>`

`templateValue` is an angular signal. `onValueChange` just sets the value back to the signal.

On the side note:
Rarely I also noticed that when I set my signal from (valueChange), it triggers a loop. Im thinking that [value] detects a new value from templateValue() signal (which was emitted from valueChange) that triggers the valueChange event again; thus repeating the emission from valuechange. So its like valueChange -> update signal -> [value] updated from signal -> valueChange (triggered again) -> loop again.

**Comment by julianpoemp** [comment]
@ptatoChi what versions of ngx-jodit, jodit and angular do you use?

**Comment by ptatoChi** [comment]
Sorry forgot to mention that

Angular 17 with
    "ngx-jodit": "^3.0.0-beta.9",
    "jodit": "^4.0.0-beta.105",

**Comment by ptatoChi** [comment]
Okay i will try :) Thank you for your input!

**Comment by julianpoemp** [comment]
I just updated my previous comment.
