### ISSUE TITLE
Icons showing text again

### ISSUE THREAD

**Issue by elementalPRESS** [julianpoemp/ngx-jodit#22]
Hi,

today I've updated to the newest release of jodit (4.0.1) and ngx-jodit (3.0.1) and have removed the script part from `angular.json` (see https://github.com/julianpoemp/ngx-jodit/issues/18). But now some icons disappearing again. Please do you have a permanent solution for this issue?

Thx and best regards,
Lars

**Comment by julianpoemp** [comment]
Do you have examples what icons are not showing? Did you follow the installation instructions and the notice about plugin imports?

**Comment by elementalPRESS** [comment]
> Do you have examples what icons are not showing? Did you follow the installation instructions and the notice about plugin imports?

From what I can see here "align", "indent", "outdent" and "source" are missing. But I'm not using all icons. So maybe some others are affected too. Then I don't use any plugins.

**Comment by julianpoemp** [comment]
@elementalPRESS in Jodit v4 each button from toolbar is a plugin itself. Some of these are imported by default (like "bold") others not (e.g. "indent", "source"). You need to import it manually:

```typescript
import 'jodit/esm/plugins/source/source.js';
import 'jodit/esm/plugins/indent/indent.js';

const config = {
  buttons: ["source", "indent"]
};

```

For more information see [here](https://github.com/julianpoemp/ngx-jodit/blob/main/libs/ngx-jodit/README.md#how-to-import-plugins).

**Comment by elementalPRESS** [comment]
> @elementalPRESS in Jodit v4 each button from toolbar is a plugin itself. Some of these are imported by default (like "bold") others not (e.g. "indent", "source"). You need to import it manually:
> 
> ```ts
> import 'jodit/esm/plugins/source/source.js';
> import 'jodit/esm/plugins/indent/indent.js';
> 
> const config = {
>   buttons: ["source", "indent"]
> };
> ```
> 
> For more information see [here](https://github.com/julianpoemp/ngx-jodit/blob/main/libs/ngx-jodit/README.md#how-to-import-plugins).

Thx a lot. It's working like a charm again now.
