### ISSUE TITLE
Off-topic: couldn't load module idle_fingers

### ISSUE THREAD

**Issue by elementalPRESS** [julianpoemp/ngx-jodit#24]
Hi,

I know that this topic is a bit off-topic and has probably nothing to do with the ngx-jodit itself. But I hope that you have an idea of a solution. Since using the ngx-jodit and the jodit latest beta versions I get the following error message:

	couldn't load module ace/theme/idle_fingers or it didn't call define

I'm using a real standard configuration and (which is the most curious) - this error comes **only** on my production system. From that point of view it's a bit hard to debug. Do you already have seen this issue?

**Comment by julianpoemp** [comment]
Hi,
does the error appear on the web console? Do you only get this one line?

If the module is an SCSS file perhaps there is a wrong import statement that only triggers on production.

If not there must be any production settings that leads to this error. Try checking the production options and/or tsconfig options.

**Comment by julianpoemp** [comment]
Did you try this?
https://stackoverflow.com/questions/71909337/aceeditoruncaught-error-couldnt-load-module-ace-theme

Btw I recommend to always censor production domains before posting.

**Comment by julianpoemp** [comment]
> Did you try this?
> https://stackoverflow.com/questions/71909337/aceeditoruncaught-error-couldnt-load-module-ace-theme
> 

This sounds like a baseHref issue. Open network tab and check for files that couldn't be found. Perhaps it's a redirection issue.

**Comment by elementalPRESS** [comment]
It becomes even more strange. It has nothing to do with jodit or ngx-jodit. It comes from another component that shouldn't been loaded at this point but for what reason ever Angular decided to do it.

But thank you so much for your support!

**Comment by julianpoemp** [comment]
Did you try the steps from my previous comment? Stackoverflow and the network tab thing?

**Comment by elementalPRESS** [comment]
> Did you try the steps from my previous comment? Stackoverflow and the network tab thing?

I tried, but without success. Maybe I've placed it at the wrong place. I have to check this a bit more in detail.

**Comment by julianpoemp** [comment]
Closing this issue. Hope you found a solution
