### ISSUE TITLE
ngx-jodit: Class extends value undefined is not a constructor or null 

### ISSUE THREAD

**Issue by achapman009** [julianpoemp/ngx-jodit#26]
When i try to load ngx-jodit in my standalone components I get an error with the esm plugins. I have my angular.json and plugin imports based on the README you provided. 

See error below:
![image](https://github.com/julianpoemp/ngx-jodit/assets/20817730/7b27b0e9-ff54-4f42-8109-385915391e38)

Standalone Imports:
![image](https://github.com/julianpoemp/ngx-jodit/assets/20817730/b196e227-f1c0-481e-b037-be1bfe6e0b62)

Do you know why this is possibly happening? 
What I find weird is if i comment out a plugin, rebuild.. then uncomment it..rebuild.. go back to the screen and my app will refresh, vite will recompile it and then it works, but on initial build it doesnt seem to see it? I am not sure if this is a vite issue, or a package issue.

Anyway, any information would be helpful. Thank you!

### Package versions

| package          | version |
|---------------|---------|
| Angular           | 17.1.0 |
| ngx-jodit         | 3.1.0 |
| jodit                | 4.0.6 |

**Comment by achapman009** [comment]
Closing issue. For anyone who also faces this:

- This happens because angular cli vite is currently not optimizing the esm imports. I also do not currently see a way to change this in the config. See https://vitejs.dev/guide/dep-pre-bundling
- I ran the command **ng cache off** and everything is working.

**Comment by achapman009** [comment]
Closing issue. For anyone who also faces this:

- This happens because angular cli vite is currently not optimizing the esm imports. I also do not currently see a way to change this in the config. See https://vitejs.dev/guide/dep-pre-bundling
- I ran the command **ng cache off** and everything is working.

**Comment by julianpoemp** [comment]
@achapman009 thanks for providing the workaround! 👍
