### ISSUE TITLE
Very large icons & no design in Jasmine Test

### ISSUE THREAD

**Issue by r-almofleh-inits** [julianpoemp/ngx-jodit#3]
Hi, i'm using your library, and i like it. Thank you for sharing it.

I have this Problem when i test my component. My component look like this:

![Bildschirmfoto 2023-01-05 um 10 33 15](https://user-images.githubusercontent.com/103039562/210749404-fe2fd84c-577e-422c-b293-a67db5870c71.png)

i have already imported the `NgxJoditModule` and `FontAwesomeModule` to my test. 

Do you have any idea?

Thanx

**Comment by julianpoemp** [comment]
it seems that there are any missing css code. Did you add the jodit css file to the list of styles in angular.json? Did you check the console if there are any issues?
