### ISSUE TITLE
Cannot install ngx-jodit with jodit v.4.0.0-beta.50

### ISSUE THREAD

**Issue by kzimny** [julianpoemp/ngx-jodit#4]
![image](https://github.com/julianpoemp/ngx-jodit/assets/12007674/fa13bb37-1345-41d4-bac3-6e3191b782ba)

Can you please help?

**Comment by kzimny** [comment]
I changed jodit to version 3.24.9 and ngx-jodit works for now. I would like to switch to version 4, beta-50 is near to final release. Would you prepare ngx-jodit v2 which is compatible with v4 of jodit?

**Comment by julianpoemp** [comment]
I just released ngx-jodit 2 beta. Please have a look for the new installation instructions here:
https://www.npmjs.com/package/ngx-jodit/v/2.0.0-beta.0

**Comment by kzimny** [comment]
This is great. Thank you very much!
