### ISSUE TITLE
Pro Plugins

### ISSUE THREAD

**Issue by cgraves09** [julianpoemp/ngx-jodit#6]
Describe the issue as detailed as possible, in a way I can reproduce it easily.

Please answer additionally:

- Is this issue related to ngx-jodit or ngx-jodit-pro? 
- jodit-pro
- What version of the package?
- latest
- What Angular version are you using?
- 15

@julianpoemp Hi i was just curious if you had an example on how to use the wrapper with some of the pro plugins?

**Comment by julianpoemp** [comment]
@cgraves09 you can activate a plugin in the options.

For example autocomplete: https://xdsoft.net/jodit/pro/docs/plugin/autocomplete/

````html
<ngx-jodit-pro [options]="{
    autocomplete: {
        sources: [
        '@mary',
	'@jain',
	'@entany',
	'@isaak',
	'@ivan',
	'@fedya',
	'@yakov',
	'@jhon',
	'@lena',
	'@elvin'
        ]
    }
}"></ngx-jodit-pro>
````

All pro plugins are part of options.

**Comment by cgraves09** [comment]
@julianpoemp Gotcha yeah thats how I was trying to implement it. For example i was trying to pop in the page break found here https://xdsoft.net/jodit/pro/docs/plugin/page-break/ but it doesnt seem to recognize it and render it into the tool bar

**Comment by cgraves09** [comment]
@julianpoemp I think i figured it out. You have to add it to the scripts "scripts": ["node_modules/jodit-pro/build/jodit.js", "node_modules/jodit-pro/build/plugins/page-break/page-break.js"]

**Comment by julianpoemp** [comment]
@cgraves09 I tested it without additional imports and you're right, it's not working. It's strange that you have to import additional files manually to get this working

**Comment by cgraves09** [comment]
@julianpoemp I do agree. I did also see that they updated the types for Jodit on the pro version too. If that helps your wrapper

**Comment by julianpoemp** [comment]
@cgraves09 thanks for the information. Unfortunately this is still the beta version. I'll consider releasing a beta v2 of ngx-jodit-pro soon like I did with ngx-jodit. Perhaps the issue with the manual imports is solved with this.

**Comment by cgraves09** [comment]
@julianpoemp Sounds good. Yeah just need to figure out why the css isnt attaching from the plugin
